# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # emplacement du package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
