name: Deploy via SSH

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: npm run test

      - name: Connect to server via SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf my-app && \
            git clone git@github.com:${{ github.repository }} my-app && \
            cd my-app && \
            git checkout ${{ github.ref_name }} && \
            npm install --save-dev cross-var@^1.1.0 && \
            cp ../.env.prod . && \
            npm run docker && \
            cd .. && \
            docker compose up -d
